version: "3.9"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  redis:
    image: redis:7.0-alpine
    hostname: localhost
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
  elasticsearch:
    image: elasticsearch:8.7.1
    hostname: localhost
    restart: on-failure
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  backend:
    build: ./backend
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mysql
      - redis
      - elasticsearch
    environment:
      BACKEND_GIN_MODE: "${BACKEND_GIN_MODE}"
      BACKEND_PORT: "${BACKEND_PORT}"
      BACKEND_JWT_SECRET_KEY: "${BACKEND_JWT_SECRET_KEY}"
      BACKEND_MYSQL_DSN: "${BACKEND_MYSQL_DSN}"
volumes:
  mysql_data: {}
  redis_data: {}
  elasticsearch_data: {}
